### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Sniki** [Sniki/Lenovo-Thinkpad-T440#1]
Some refinements to be done to polish the experience:

- [ ] Find a solution for users with different keyboard layouts to separate right option key from left Option key so they can use these specific keys for their language.
Should fix issues with users on different keyboard layouts than US.
- [ ] Finish the EDID patching section of the guide and upload screenshots so users can enable secure boot without garbled screen.
- [x] Investigate the Audio situation with ALCPlugFix on whether to fix or switch to ALC-Verb
- [x] Remove .DS_Store files
